# Generated by Django 4.2.6 on 2023-10-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blog/media/blog/default/default.jpg', upload_to='blog/media/'),
        ),
    ]
